# Generated by Django 5.1.3 on 2024-11-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_marked_on_time_attendancewindow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10),
        ),
        migrations.DeleteModel(
            name='AttendanceWindow',
        ),
    ]
