from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import AttendanceViewSet

# Create a router for the AttendanceViewSet
router = DefaultRouter()
router.register(r'', AttendanceViewSet, basename='attendance')

urlpatterns = [
    path('', include(router.urls)),  # Includes all routes generated by the router
]
