# Generated by Django 5.1.3 on 2024-11-24 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_popularcourse'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='activeuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='apirequestlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='PopularCourse',
        ),
        migrations.RemoveField(
            model_name='courseaccesslog',
            name='course_id',
        ),
        migrations.AddField(
            model_name='courseaccesslog',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ActiveUser',
        ),
        migrations.DeleteModel(
            name='APIRequestLog',
        ),
    ]
